spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/codein_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      location: C:\Users\kdha0\Documents\GitHub\codein\front\public\images\
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false




